# Generated by Django 4.2.7 on 2023-12-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_choices_answer_date_choices_answer_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='answer_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
