# Generated by Django 4.2.7 on 2023-12-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_alter_choices_answer_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date', '-updated_at']},
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
