# Generated by Django 4.2.7 on 2023-12-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0004_alter_question_options_question_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choices',
            options={'ordering': ['-answer_date', '-answer_update']},
        ),
        migrations.AddField(
            model_name='choices',
            name='answer_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='choices',
            name='answer_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
