# Generated by Django 4.2.7 on 2023-12-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0007_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
