# Generated by Django 4.2.7 on 2023-12-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0009_likequestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likequestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vaccines.question'),
        ),
    ]
