# Generated by Django 4.2.7 on 2023-12-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0010_alter_likequestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
