# Generated by Django 4.2.7 on 2023-12-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0011_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-updated_at', '-pub_date']},
        ),
    ]
