# Generated by Django 4.2.7 on 2024-01-27 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0013_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmarks',
            name='time_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='time_updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
