# Generated by Django 4.2.7 on 2024-01-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0014_bookmarks_time_created_bookmarks_time_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarks',
            options={'ordering': ['-time_updated', 'time_created']},
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
