# Generated by Django 4.2.7 on 2024-01-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0015_alter_bookmarks_options_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_tesxt',
            field=models.CharField(max_length=5000),
        ),
    ]
