# Generated by Django 4.2.7 on 2024-01-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0016_alter_question_question_tesxt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='choice_text',
            field=models.TextField(),
        ),
    ]
