# Generated by Django 4.2.7 on 2024-01-29 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0017_alter_choices_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_attended',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
