# Generated by Django 4.2.7 on 2024-01-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0018_userprofile_occupation_userprofile_school_attended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
