# Generated by Django 4.2.7 on 2024-01-29 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0019_alter_userprofile_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_tesxt',
        ),
        migrations.AddField(
            model_name='question',
            name='question_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
